### ISSUE TITLE
Is the metric "dynamic range independent image quality metric (DRIM)" also available in the code for evaluation?

### ISSUE THREAD

**Issue by juhuitseng** [viengiaan/Single-Shot-HDR-Imaging-with-MSCNN#2]
Is the metric "dynamic range independent image quality metric (DRIM)" also available in your code for evaluation? Thanks in advance:)

**Comment by viengiaan** [comment]
I have attached the DRIM and a simple example to use it. Hope this is helpful for your research.
[DRIM.zip](https://github.com/viengiaan/Single-Shot-HDR-Imaging-with-MSCNN/files/7333934/DRIM.zip)

**Comment by juhuitseng** [comment]
Thank you very much:)
